name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
  #schedule:
  #  - cron: "*/5 * * * *"
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - master
      - main
      - dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: AP Github Action
          cx_tenant: dp_wp_account
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.oauthclient }}
          cx_client_secret: ${{ secrets.oauthsecret }}
          #additional_params: --apikey ${{ secrets.apisecret2 }}
          #additional_params: --sast-preset-name "Checkmarx Default" --tags "blueberry"
          additional_params: --sast-preset-name "Checkmarx Default" --debug
